/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as CountSheetHoldersRouteImport } from './routes/count-sheet-holders'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as RequestQuoteRouteImport } from './routes/request-quote'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SoftwareRouteImport } from './routes/software'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProductCategorySlugRouteImport } from './routes/product-category.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ProgrammesSlugRouteImport } from './routes/programmes.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as SoftwareSlugRouteImport } from './routes/software.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const CountSheetHoldersRoute = CountSheetHoldersRouteImport.update({
  id: '/count-sheet-holders',
  path: '/count-sheet-holders',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: '/request-quote',
  path: '/request-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareRoute = SoftwareRouteImport.update({
  id: '/software',
  path: '/software',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductCategorySlugRoute = ProductCategorySlugRouteImport.update({
  id: '/product-category/$slug',
  path: '/product-category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const ProgrammesSlugRoute = ProgrammesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProgrammesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const SoftwareSlugRoute = SoftwareSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SoftwareRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/count-sheet-holders': typeof CountSheetHoldersRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/programmes': typeof ProgrammesRouteWithChildren
  '/request-quote': typeof RequestQuoteRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/software': typeof SoftwareRouteWithChildren
  '/terms': typeof TermsRoute
  '/product-category/$slug': typeof ProductCategorySlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/software/$slug': typeof SoftwareSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/count-sheet-holders': typeof CountSheetHoldersRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/programmes': typeof ProgrammesRouteWithChildren
  '/request-quote': typeof RequestQuoteRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/software': typeof SoftwareRouteWithChildren
  '/terms': typeof TermsRoute
  '/product-category/$slug': typeof ProductCategorySlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/software/$slug': typeof SoftwareSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact-us': typeof ContactUsRoute
  '/count-sheet-holders': typeof CountSheetHoldersRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/programmes': typeof ProgrammesRouteWithChildren
  '/request-quote': typeof RequestQuoteRoute
  '/resources': typeof ResourcesRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/software': typeof SoftwareRouteWithChildren
  '/terms': typeof TermsRoute
  '/product-category/$slug': typeof ProductCategorySlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/software/$slug': typeof SoftwareSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact-us'
    | '/count-sheet-holders'
    | '/faq'
    | '/privacy'
    | '/products'
    | '/programmes'
    | '/request-quote'
    | '/resources'
    | '/search'
    | '/services'
    | '/software'
    | '/terms'
    | '/product-category/$slug'
    | '/products/$slug'
    | '/programmes/$slug'
    | '/services/$slug'
    | '/software/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact-us'
    | '/count-sheet-holders'
    | '/faq'
    | '/privacy'
    | '/products'
    | '/programmes'
    | '/request-quote'
    | '/resources'
    | '/search'
    | '/services'
    | '/software'
    | '/terms'
    | '/product-category/$slug'
    | '/products/$slug'
    | '/programmes/$slug'
    | '/services/$slug'
    | '/software/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact-us'
    | '/count-sheet-holders'
    | '/faq'
    | '/privacy'
    | '/products'
    | '/programmes'
    | '/request-quote'
    | '/resources'
    | '/search'
    | '/services'
    | '/software'
    | '/terms'
    | '/product-category/$slug'
    | '/products/$slug'
    | '/programmes/$slug'
    | '/services/$slug'
    | '/software/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactUsRoute: typeof ContactUsRoute
  CountSheetHoldersRoute: typeof CountSheetHoldersRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProgrammesRoute: typeof ProgrammesRouteWithChildren
  RequestQuoteRoute: typeof RequestQuoteRoute
  ResourcesRoute: typeof ResourcesRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SoftwareRoute: typeof SoftwareRouteWithChildren
  TermsRoute: typeof TermsRoute
  ProductCategorySlugRoute: typeof ProductCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/count-sheet-holders': {
      id: '/count-sheet-holders'
      path: '/count-sheet-holders'
      fullPath: '/count-sheet-holders'
      preLoaderRoute: typeof CountSheetHoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-quote': {
      id: '/request-quote'
      path: '/request-quote'
      fullPath: '/request-quote'
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software': {
      id: '/software'
      path: '/software'
      fullPath: '/software'
      preLoaderRoute: typeof SoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-category/$slug': {
      id: '/product-category/$slug'
      path: '/product-category/$slug'
      fullPath: '/product-category/$slug'
      preLoaderRoute: typeof ProductCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/programmes/$slug': {
      id: '/programmes/$slug'
      path: '/$slug'
      fullPath: '/programmes/$slug'
      preLoaderRoute: typeof ProgrammesSlugRouteImport
      parentRoute: typeof ProgrammesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/software/$slug': {
      id: '/software/$slug'
      path: '/$slug'
      fullPath: '/software/$slug'
      preLoaderRoute: typeof SoftwareSlugRouteImport
      parentRoute: typeof SoftwareRoute
    }
  }
}

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ProgrammesRouteChildren {
  ProgrammesSlugRoute: typeof ProgrammesSlugRoute
}

const ProgrammesRouteChildren: ProgrammesRouteChildren = {
  ProgrammesSlugRoute: ProgrammesSlugRoute,
}

const ProgrammesRouteWithChildren = ProgrammesRoute._addFileChildren(
  ProgrammesRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface SoftwareRouteChildren {
  SoftwareSlugRoute: typeof SoftwareSlugRoute
}

const SoftwareRouteChildren: SoftwareRouteChildren = {
  SoftwareSlugRoute: SoftwareSlugRoute,
}

const SoftwareRouteWithChildren = SoftwareRoute._addFileChildren(
  SoftwareRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactUsRoute: ContactUsRoute,
  CountSheetHoldersRoute: CountSheetHoldersRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProgrammesRoute: ProgrammesRouteWithChildren,
  RequestQuoteRoute: RequestQuoteRoute,
  ResourcesRoute: ResourcesRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SoftwareRoute: SoftwareRouteWithChildren,
  TermsRoute: TermsRoute,
  ProductCategorySlugRoute: ProductCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
